In [1]:
import os
import time
from pathlib import Path
import polars as pl
import duckdb

In [2]:
DATA_PATH = "../data/raw/chicago_crimes.csv"
print(f"Ukuran file: {Path(DATA_PATH).stat().st_size / 1024**2:.1f} MB")

Ukuran file: 1825.6 MB

In [3]:
lf = pl.scan_csv(
    DATA_PATH,
    try_parse_dates=True,
    schema_overrides={
        "IUCR": pl.Utf8,
        "FBI Code": pl.Utf8,
        "Case Number": pl.Utf8,
    },
    infer_schema_length=10000,
    ignore_errors=True,
)
print(lf.collect_schema())

Schema({'ID': Int64, 'Case Number': String, 'Date': String, 'Block': String, 'IUCR': String, 'Primary Type': String, 'Description': String, 'Location Description': String, 'Arrest': Boolean, 'Domestic': Boolean, 'Beat': Int64, 'District': Int64, 'Ward': Int64, 'Community Area': Int64, 'FBI Code': String, 'X Coordinate': Int64, 'Y Coordinate': Int64, 'Year': Int64, 'Updated On': String, 'Latitude': Float64, 'Longitude': Float64, 'Location': String})

In [4]:
n_rows = lf.select(pl.len()).collect().item()
print(f"Jumlah baris: {n_rows:,}")

Jumlah baris: 8,104,658

In [5]:
con = duckdb.connect()
con.sql(f"SUMMARIZE SELECT * FROM read_csv_auto('{DATA_PATH}', ignore_errors=true)").pl()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (22, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ column_nam ┆ column_ty ┆ min       ┆ max       ┆ … ┆ q50       ┆ q75       ┆ count   ┆ null_perc │
│ e          ┆ pe        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---     ┆ entage    │
│ ---        ┆ ---       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i64     ┆ ---       │
│ str        ┆ str       ┆           ┆           ┆   ┆           ┆           ┆         ┆ decimal[9 │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ ,2]       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ ID         ┆ BIGINT    ┆ 634       ┆ 13525542  ┆ … ┆ 7302679   ┆ 10508633  ┆ 8104658 ┆ 0.00      │
│ Case       ┆ VARCHAR   ┆ 01G050460 ┆ ZZZ199957 ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│ Number     ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Date       ┆ TIMESTAMP ┆ 2001-01-0 ┆ 2024-07-0 ┆ … ┆ 2010-01-0 ┆ 2016-05-0 ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 1         ┆ 4         ┆   ┆ 5 20:15:3 ┆ 9 20:04:0 ┆         ┆           │
│            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 0.010639  ┆ 6.697114  ┆         ┆           │
│ Block      ┆ VARCHAR   ┆ 0000X E   ┆ XX        ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 100 PL    ┆ UNKNOWN   ┆   ┆           ┆           ┆         ┆           │
│ IUCR       ┆ VARCHAR   ┆ 0110      ┆ 9901      ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ Year       ┆ BIGINT    ┆ 2001      ┆ 2024      ┆ … ┆ 2009      ┆ 2016      ┆ 8104658 ┆ 0.00      │
│ Updated On ┆ TIMESTAMP ┆ 2006-03-3 ┆ 2024-07-1 ┆ … ┆ 2018-02-2 ┆ 2018-02-2 ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 1         ┆ 1         ┆   ┆ 8         ┆ 8 23:13:3 ┆         ┆           │
│            ┆           ┆ 22:03:38  ┆ 15:45:11  ┆   ┆ 15:56:25  ┆ 0.693857  ┆         ┆           │
│ Latitude   ┆ DOUBLE    ┆ 36.619446 ┆ 42.022910 ┆ … ┆ 41.856426 ┆ 41.906841 ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 395       ┆ 333       ┆   ┆ 88397502  ┆ 571306124 ┆         ┆           │
│ Longitude  ┆ DOUBLE    ┆ -91.68656 ┆ -87.52452 ┆ … ┆ -87.66575 ┆ -87.62826 ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 5684      ┆ 9378      ┆   ┆ 98816076  ┆ 755679815 ┆         ┆           │
│ Location   ┆ VARCHAR   ┆ (36.61944 ┆ (42.02291 ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 6395, -91 ┆ 0333, -87 ┆   ┆           ┆           ┆         ┆           │
│            ┆           ┆ .68656568 ┆ .67719200 ┆   ┆           ┆           ┆         ┆           │
│            ┆           ┆ 4)        ┆ 4)        ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [6]:
lf.null_count().collect()

shape: (1, 22)
┌─────┬─────────────┬──────┬───────┬───┬────────────┬──────────┬───────────┬──────────┐
│ ID  ┆ Case Number ┆ Date ┆ Block ┆ … ┆ Updated On ┆ Latitude ┆ Longitude ┆ Location │
│ --- ┆ ---         ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---      │
│ u32 ┆ u32         ┆ u32  ┆ u32   ┆   ┆ u32        ┆ u32      ┆ u32       ┆ u32      │
╞═════╪═════════════╪══════╪═══════╪═══╪════════════╪══════════╪═══════════╪══════════╡
│ 0   ┆ 0           ┆ 0    ┆ 0     ┆ … ┆ 0          ┆ 89642    ┆ 89642     ┆ 89642    │
└─────┴─────────────┴──────┴───────┴───┴────────────┴──────────┴───────────┴──────────┘

In [7]:
lf. with_columns(
    pl.col("Date").str.to_datetime("%m/%d/%Y %I:%M:%S %p", strict=False).alias("parsed_date")
).select(
    pl.col("parsed_date").min().alias("tanggal_awal"),
    pl.col("parsed_date").max().alias("tanggal_akhir"),
    pl.col("Year").min().alias("tahun_awal"),
    pl.col("Year").max().alias("tahun_akhir"),
    pl.col("Latitude").min().alias("lat_min"),
    pl.col("Latitude").max().alias("lat_max"),
    pl.col("Longitude").min().alias("lon_min"),
    pl.col("Longitude").max().alias("lon_max"),
).collect()

shape: (1, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ tanggal_aw ┆ tanggal_ak ┆ tahun_awal ┆ tahun_akhi ┆ lat_min   ┆ lat_max  ┆ lon_min   ┆ lon_max   │
│ al         ┆ hir        ┆ ---        ┆ r          ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ i64        ┆ ---        ┆ f64       ┆ f64      ┆ f64       ┆ f64       │
│ datetime[μ ┆ datetime[μ ┆            ┆ i64        ┆           ┆          ┆           ┆           │
│ s]         ┆ s]         ┆            ┆            ┆           ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2001-01-01 ┆ 2024-07-04 ┆ 2001       ┆ 2024       ┆ 36.619446 ┆ 42.02291 ┆ -91.68656 ┆ -87.52452 │
│ 00:00:00   ┆ 00:00:00   ┆            ┆            ┆           ┆          ┆ 6         ┆ 9         │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘

In [8]:
n_unik = lf.unique().select(pl.len()).collect().item()
n_id_unik = lf.select(pl.col("ID").n_unique()).collect().item()

print(f"Baris duplikat penuh : {n_rows - n_unik:,}")
print(f"Duplikat kolom ID    : {n_rows - n_id_unik:,}")

Baris duplikat penuh : 0
Duplikat kolom ID    : 0

In [9]:
lf.group_by("Primary Type").agg(
    pl.len().alias("jumlah_kasus"),
    (pl.col("Arrest").mean() * 100).round(2).alias("persen_arrest"),
).sort("jumlah_kasus", descending=True).head(10).collect()

shape: (10, 3)
┌─────────────────────┬──────────────┬───────────────┐
│ Primary Type        ┆ jumlah_kasus ┆ persen_arrest │
│ ---                 ┆ ---          ┆ ---           │
│ str                 ┆ u32          ┆ f64           │
╞═════════════════════╪══════════════╪═══════════════╡
│ THEFT               ┆ 1713138      ┆ 10.95         │
│ BATTERY             ┆ 1478402      ┆ 21.78         │
│ CRIMINAL DAMAGE     ┆ 923178       ┆ 6.58          │
│ NARCOTICS           ┆ 754665       ┆ 99.35         │
│ ASSAULT             ┆ 535559       ┆ 20.66         │
│ OTHER OFFENSE       ┆ 503568       ┆ 17.56         │
│ BURGLARY            ┆ 433444       ┆ 5.71          │
│ MOTOR VEHICLE THEFT ┆ 406982       ┆ 7.83          │
│ DECEPTIVE PRACTICE  ┆ 366611       ┆ 12.86         │
│ ROBBERY             ┆ 305289       ┆ 9.22          │
└─────────────────────┴──────────────┴───────────────┘