In [1]:
from pathlib import Path
import duckdb
import polars as pl

In [2]:
# Setup Path: Mundur satu langkah dari folder 'notebooks' menggunakan .parent
PROJECT_ROOT = Path.cwd().resolve().parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "chicago_crimes.csv"
OUTPUT_PATH = PROJECT_ROOT / "data" / "processed" / "chicago_crimes_clean.parquet"

# Menggunakan LazyFrame agar hemat RAM untuk memproses 8,1 juta baris
lf = pl.scan_csv(
    DATA_PATH,
    try_parse_dates=True,
    ignore_errors=True,
    infer_schema_length=10000
)

# Cleaning 
rename_map = {col: col.strip().lower().replace(" ", "_") for col in lf.collect_schema().names()}
lf_std = lf.rename(rename_map)

print("Succsess! Total kolom:", len(rename_map))

Succsess! Total kolom: 22

In [3]:
con = duckdb.connect()

# Menjalankan profiling langsung dari file mentah CSV
profil = con.execute(f"SUMMARIZE SELECT * FROM read_csv_auto('{DATA_PATH}', ignore_errors=true)").pl()
profil

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (22, 12)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬─────────┬───────────┐
│ column_nam ┆ column_ty ┆ min       ┆ max       ┆ … ┆ q50       ┆ q75       ┆ count   ┆ null_perc │
│ e          ┆ pe        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---     ┆ entage    │
│ ---        ┆ ---       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i64     ┆ ---       │
│ str        ┆ str       ┆           ┆           ┆   ┆           ┆           ┆         ┆ decimal[9 │
│            ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆ ,2]       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════╪═══════════╡
│ ID         ┆ BIGINT    ┆ 634       ┆ 13525542  ┆ … ┆ 7287280   ┆ 10535114  ┆ 8104658 ┆ 0.00      │
│ Case       ┆ VARCHAR   ┆ 01G050460 ┆ ZZZ199957 ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│ Number     ┆           ┆           ┆           ┆   ┆           ┆           ┆         ┆           │
│ Date       ┆ TIMESTAMP ┆ 2001-01-0 ┆ 2024-07-0 ┆ … ┆ 2009-12-2 ┆ 2016-05-1 ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 1         ┆ 4         ┆   ┆ 1 10:34:3 ┆ 6 01:15:1 ┆         ┆           │
│            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 9.946107  ┆ 9.433226  ┆         ┆           │
│ Block      ┆ VARCHAR   ┆ 0000X E   ┆ XX        ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 100 PL    ┆ UNKNOWN   ┆   ┆           ┆           ┆         ┆           │
│ IUCR       ┆ VARCHAR   ┆ 0110      ┆ 9901      ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 0.00      │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …       ┆ …         │
│ Year       ┆ BIGINT    ┆ 2001      ┆ 2024      ┆ … ┆ 2010      ┆ 2016      ┆ 8104658 ┆ 0.00      │
│ Updated On ┆ TIMESTAMP ┆ 2006-03-3 ┆ 2024-07-1 ┆ … ┆ 2018-02-2 ┆ 2018-02-2 ┆ 8104658 ┆ 0.00      │
│            ┆           ┆ 1         ┆ 1         ┆   ┆ 8         ┆ 8 20:13:0 ┆         ┆           │
│            ┆           ┆ 22:03:38  ┆ 15:45:11  ┆   ┆ 15:56:25  ┆ 4.110543  ┆         ┆           │
│ Latitude   ┆ DOUBLE    ┆ 36.619446 ┆ 42.022910 ┆ … ┆ 41.856377 ┆ 41.907041 ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 395       ┆ 333       ┆   ┆ 18805103  ┆ 23884905  ┆         ┆           │
│ Longitude  ┆ DOUBLE    ┆ -91.68656 ┆ -87.52452 ┆ … ┆ -87.66572 ┆ -87.62831 ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 5684      ┆ 9378      ┆   ┆ 607670047 ┆ 32307817  ┆         ┆           │
│ Location   ┆ VARCHAR   ┆ (36.61944 ┆ (42.02291 ┆ … ┆ null      ┆ null      ┆ 8104658 ┆ 1.11      │
│            ┆           ┆ 6395, -91 ┆ 0333, -87 ┆   ┆           ┆           ┆         ┆           │
│            ┆           ┆ .68656568 ┆ .67719200 ┆   ┆           ┆           ┆         ┆           │
│            ┆           ┆ 4)        ┆ 4)        ┆   ┆           ┆           ┆         ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴─────────┴───────────┘

In [4]:
# Cek sebaran null
print(lf_std.null_count().collect())

# Parsing format tanggal dan menghapus missing values pada kolom krusial
lf_missing_handled = (
    lf_std
    .with_columns(
        pl.col("date").str.to_datetime("%m/%d/%Y %I:%M:%S %p", strict=False).alias("datetime")
    )
    .drop_nulls(subset=["datetime", "latitude", "longitude", "primary_type"])
)

shape: (1, 22)
┌─────┬─────────────┬──────┬───────┬───┬────────────┬──────────┬───────────┬──────────┐
│ id  ┆ case_number ┆ date ┆ block ┆ … ┆ updated_on ┆ latitude ┆ longitude ┆ location │
│ --- ┆ ---         ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---      │
│ u32 ┆ u32         ┆ u32  ┆ u32   ┆   ┆ u32        ┆ u32      ┆ u32       ┆ u32      │
╞═════╪═════════════╪══════╪═══════╪═══╪════════════╪══════════╪═══════════╪══════════╡
│ 0   ┆ 0           ┆ 0    ┆ 0     ┆ … ┆ 0          ┆ 89642    ┆ 89642     ┆ 89642    │
└─────┴─────────────┴──────┴───────┴───┴────────────┴──────────┴───────────┴──────────┘

In [6]:
# Batas Geografis Chicago (Domain Knowledge):
# Latitude : 41.60 s/d 42.05
# Longitude: -87.95 s/d -87.50

lf_outlier_handled = lf_missing_handled.filter(
    pl.col("latitude").is_between(41.60, 42.05) &
    pl.col("longitude").is_between(-87.95, -87.50) &
    (pl.col("datetime").dt.year() >= 2001) &
    (pl.col("datetime").dt.year() <= 2026)
)

In [7]:
lf_dedup = lf_outlier_handled.unique(subset=["id"], keep="first")

In [8]:
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

# Mengeksekusi seluruh pipeline secara streaming dan menyimpan hasilnya
lf_dedup.sink_parquet(OUTPUT_PATH)

print(f"Data bersih berhasil disimpan dalam format Parquet di: {OUTPUT_PATH.name}")

Data bersih berhasil disimpan dalam format Parquet di: chicago_crimes_clean.parquet

In [9]:
# Menguji file Parquet hasil pembersihan menggunakan DuckDB
validasi = con.execute(f"""
    SELECT
        COUNT(*) AS total_baris_bersih,
        SUM(CASE WHEN latitude IS NULL THEN 1 ELSE 0 END) AS sisa_null_lat,
        SUM(CASE WHEN datetime IS NULL THEN 1 ELSE 0 END) AS sisa_null_date,
        SUM(CASE WHEN latitude < 41.60 OR latitude > 42.05 THEN 1 ELSE 0 END) AS sisa_outlier_lat,
        SUM(CASE WHEN longitude < -87.95 OR longitude > -87.50 THEN 1 ELSE 0 END) AS sisa_outlier_lon
    FROM read_parquet('{OUTPUT_PATH}')
""").pl()

validasi

shape: (1, 5)
┌────────────────────┬───────────────┬────────────────┬──────────────────┬──────────────────┐
│ total_baris_bersih ┆ sisa_null_lat ┆ sisa_null_date ┆ sisa_outlier_lat ┆ sisa_outlier_lon │
│ ---                ┆ ---           ┆ ---            ┆ ---              ┆ ---              │
│ i64                ┆ decimal[38,0] ┆ decimal[38,0]  ┆ decimal[38,0]    ┆ decimal[38,0]    │
╞════════════════════╪═══════════════╪════════════════╪══════════════════╪══════════════════╡
│ 8014867            ┆ 0             ┆ 0              ┆ 0                ┆ 0                │
└────────────────────┴───────────────┴────────────────┴──────────────────┴──────────────────┘